CREATE TABLE [dbo].[MCTypesCard]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[Name] VARCHAR(50) NOT NULL,
	[LastUpdated] DATETIME NOT NULL DEFAULT GETDATE(),
	[Available] BIT NOT NULL DEFAULT '1'
)
