CREATE TABLE [dbo].[MCUsers]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[MCRolesId] UNIQUEIDENTIFIER NOT NULL REFERENCES [MCRoles]([Id]),
	[UserName] VARCHAR(50) NOT NULL,
	[Email] VARCHAR(150) NOT NULL,
	[Password] VARCHAR(50) NOT NULL,
	[FirstName] VARCHAR(50) NOT NULL,
	[LastName] vARCHAR(50) NOT NULL,
	[LastUpdated] DATETIME NOT NULL DEFAULT GETDATE(),
	[Available] BIT NOT NULL DEFAULT '1'
)
